import 'package:stacked/stacked.dart';

class GalleryViewModel extends BaseViewModel {
  final imageUrls = [
    "https://live.tourofcrete.gr/images/cmbt-gallery/1.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/2.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/3.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/4.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/5.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/6.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/7.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/8.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/10.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/11.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/12.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/13.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/14.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/15.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/16.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/17.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/18.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/19.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/20.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/21.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/22.jpg",
    "https://live.tourofcrete.gr/images/cmbt-gallery/23.jpg",
  ];

  final imageDescriptions = [
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ];

  final imageDescriptions2 = [
    'Το όνειρο',
    'Η πρόκληση',
    'Δύναμη',
    'Γαλάζιο',
    'Απόκρυφο',
    'Γαλήνη',
    'Μπλε',
    'Άγριο',
    'Ξέγνοιαστο',
    'Ιερό',
    'Δράση',
    'Αδρεναλίνη',
    'Γαλάζιο',
    'Απέραντο',
    'Μπλε',
    'Άγριο',
    'Ξέγνοιαστο',
    'Ιερό',
    'Δράση',
    'Αδρεναλίνη',
    'Γαλάζιο',
    'Απέραντο',
  ];
}
